include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    
    # Error prevention
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    
    # Best practices
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    sort_pub_dependencies: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    
    # Documentation
    public_member_api_docs: false
    
    # Naming
    non_constant_identifier_names: true
    constant_identifier_names: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore
